### ISSUE TITLE
Welcome @jurezitnik!

### ISSUE THREAD

**Issue by igoramadas** [strautomator/contact#8]
Hi @jurezitnik,

Thanks for the support! Please send me your Strava ID here (or via [info@strautomator.com](mailto:info@strautomator.com)) so I can switch your Strautomator account to PRO manually. Unfortunately the system could not find your account based on username / first name / last name.

Best,

Igor

**Comment by jurezitnik** [comment]
Hi Igor,

my Strava IDAccount ID is *64836901*.

I wanted to subscribe by PayPal but for some reason I was unable to do with
any of my credit cards and my bank account. Never happened before and my
Netflix subscription is via PayPal. I've tried to searchin the issue on the
web and some people are saying it is probably a country/bank issue since I
am from Slovenia and subscriptions could be processed in PayPal differently
than one time payments. Do you happen to know if anyone else had similar
issues when wanting to subscribe via paypal?

I don't mind the GitHub way of subscription, as the app is exactly what I
needed (I wish I knew it existed before). Just letting you know what I have
experienced.

Regards,

Jure

V V tor., 13. avg. 2024 ob 09:49 je oseba Igor Ramadas <
***@***.***> napisala:

**Comment by igoramadas** [comment]
I checked the logs but could not find anything out of the ordinary. Indeed, there are a bunch of requests for your user that never got approved on the side of PayPal. But no idea why, as I have a bunch of subscribers from Slovenia registered.

I'll contact PayPal and see if they can give more information. Thanks for the heads up.

Your account was switched to PRO now. :-)

**Comment by jurezitnik** [comment]
I'd be really grateful for any information from Paypal regarding this. In
the past if there was a problem with an order in an online store, the
online store was always able to get a better explanation for the issue than
me from Paypal. Since you have subscribers from Slovenia, It could also be
an issue with my account. Either way, it would be nice to know so it can be
solved.

The specific issue I had with Paypal was order confirmation and money
transaction before the final order confirmation screen was displayed when
using "checkout with Paypal". Normally, you would get redirected to the
online store from Paypal to make a final confirmation of the purchase. In
two different cases the transaction proceeded without this confirmation and
was rather inconvenient for me, since I used "checkout with Paypal" option
to firstly find out what the shipping cost for the order would be.
In both of these cases, the online store told me that this is a known issue
and Paypal was aware of it. Paypal did provide an explanation to me, that
this was an issue with the webpage configuration and incorrectly setting up
Paypal in the backend of the online store I was ordering from.

Thanks for the PRO.

Regards,

Jure

V V tor., 13. avg. 2024 ob 16:04 je oseba Igor Ramadas <
***@***.***> napisala:
